-- +goose Up
-- +goose StatementBegin
ALTER TABLE layer1_message
  ADD content text;
ALTER TABLE layer2_message
  ADD content text;

ALTER TABLE layer1_message
  DROP COLUMN sender,
  DROP COLUMN target,
  DROP COLUMN value,
  DROP COLUMN fee,
  DROP COLUMN gas_limit,
  DROP COLUMN deadline,
  DROP COLUMN calldata;
ALTER TABLE layer2_message
  DROP COLUMN sender,
  DROP COLUMN target,
  DROP COLUMN value,
  DROP COLUMN fee,
  DROP COLUMN gas_limit,
  DROP COLUMN deadline,
  DROP COLUMN calldata;

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
ALTER TABLE layer1_message
  ADD sender varchar,
  ADD target varchar,
  ADD value bigint,
  ADD fee bigint,
  ADD gas_limit bigint,
  ADD deadline bigint,
  ADD calldata text;
ALTER TABLE layer2_message
  ADD sender varchar,
  ADD target varchar,
  ADD value bigint,
  ADD fee bigint,
  ADD gas_limit bigint,
  ADD deadline bigint,
  ADD calldata text;

ALTER TABLE layer1_message
  DROP COLUMN content;
ALTER TABLE layer2_message
  DROP COLUMN content;

-- +goose StatementEnd
