coverage:
  status:
    project: off
    patch: off
flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: rollup
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: bridge-history-api
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: common
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: coordinator
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: database
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: prover
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - name: contracts
      statuses:
        - type: project
          target: auto
          threshold: 1%
