[package]
name = "libzkp-c"
version.workspace = true
edition.workspace = true

[lib]
name = "zkp"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libzkp = { path = "../libzkp" }
l2geth = { path = "../l2geth"}
tracing.workspace = true
