[package]
name = "prover"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axiom-sdk.workspace = true
scroll-zkvm-types.workspace = true
scroll-zkvm-prover.workspace = true
libzkp = { path = "../libzkp"}
scroll-proving-sdk = { git = "https://github.com/scroll-tech/scroll-proving-sdk.git", rev = "504e71f" }
serde.workspace = true
serde_json.workspace = true
eyre.workspace = true
tracing.workspace = true

futures-util = "0.3"

reqwest = { version = "0.12", features = ["gzip", "stream"] }
hex = "0.4.3"

jiff.workspace = true
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
url = { version = "2.5.4", features = ["serde"] }
tempfile = "3.24"
backon = "1.6.0"

[features]
default = []
cuda = ["scroll-zkvm-prover/cuda"]
