#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [526871621, 1760027407, 1098199902, 1396863697, 1161283929, 833529245, 764849238, 1980368151];
