#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1949520463, 1608762743, 907128747, 1467732862, 772471692, 1337907693, 1240830371, 1477536382];
