#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [446591363, 967923404, 1527265174, 1984989696, 378361383, 482197944, 1220893050, 155477006];
