#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [327331838, 22681549, 117500213, 1286733731, 1254077267, 1594297936, 31131681, 1042165191];
