version: '3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scroll
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  proposer-tool:
    build:
      context: ..
      dockerfile: ./rollup/proposer_tool.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: [
      "--config", "/app/conf/proposer-tool-config.json",
      "--genesis", "/app/conf/proposer-tool-genesis.json",
      "--min-codec-version", "7",
      "--start-l2-block", "10000",
      "--log.debug", "--verbosity", "3"
    ]
    volumes:
      - ./proposer-tool-config.json:/app/conf/proposer-tool-config.json
      - ./proposer-tool-genesis.json:/app/conf/proposer-tool-genesis.json
    restart: unless-stopped

volumes:
  postgres_data:
