#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1522893519, 825934780, 915193979, 420256347, 1025593140, 1868643902, 869461277, 778266172];
