#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1443243841, 1004366406, 2003092941, 1325139171, 1093586017, 1842955945, 1478923252, 128760176];
