roller_name = "my_roller"
keystore_path = "keystore.json"
keystore_password = "roller-pwd"
<<<<<<< HEAD
scroll_url = "ws://localhost:8391"
=======
coordinator_url = "ws://localhost:9000"
>>>>>>> staging
db_path = "bbolt_db"

[prover]
mock_mode = false
params_path = "params"
seed_path = "seed"