roller_name = "my_roller"
keystore_path = "keystore"
keystore_password = "roller-pwd"
scroll_url = "ws://localhost:8291"
db_path = "bbolt_db"

[prover]
mock_mode = false
params_path = "params"
seed_path = "seed"