[package]
name = "scroll-zkvm-types"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version = "0.2.0"

[dependencies]
types-base = { path = "base", package = "scroll-zkvm-circuit-input-types-base"}
types-agg = { path = "aggregation", package = "scroll-zkvm-circuit-input-types-aggregation"}
types-chunk = { path = "chunk", package = "scroll-zkvm-circuit-input-types-chunk"}
types-batch = { path = "batch", package = "scroll-zkvm-circuit-input-types-batch"}
types-bundle = { path = "bundle", package = "scroll-zkvm-circuit-input-types-bundle"}


