pub mod config;
mod coordinator_client;
mod geth_client;
mod key_signer;
mod prover;
mod task_cache;
mod task_processor;
pub mod types;
mod utils;
pub mod version;
mod zk_circuits_handler;
pub mod prover_core;