[package]
name = "scroll-zkvm-circuit-input-types-bundle"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version = "0.2.0"

[dependencies]
alloy-primitives = { workspace = true, default-features = false, features = ["std", "map-hashbrown", "map-fxhash", "rkyv"] }
rkyv.workspace = true
serde.workspace = true
itertools.workspace = true
vm-zstd = { workspace = true }

types-base = { path = "../base", package = "scroll-zkvm-circuit-input-types-base"}
types-agg = { path = "../aggregation", package = "scroll-zkvm-circuit-input-types-aggregation"}

[features]
default = []
