[package]
name = "scroll-zkvm-prover"
edition.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
scroll-zkvm-circuit-input-types.workspace = true
scroll-zkvm-verifier.workspace = true

alloy-primitives = { workspace = true, default-features = false, features = ["std", "map-hashbrown", "map-fxhash", "rkyv"] }
rkyv.workspace = true
bincode_v1.workspace = true
sbv-primitives = { workspace = true }
tracing.workspace = true
metrics.workspace = true
metrics-util.workspace = true
metrics-tracing-context.workspace = true
snark-verifier-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true

openvm-circuit = { workspace = true }
openvm-continuations.workspace = true
openvm-native-circuit = { workspace = true, default-features = false }
openvm-native-recursion = { workspace = true }
openvm-sdk = { workspace = true }
openvm-stark-sdk = { workspace = true, default-features = false }

once_cell.workspace = true
base64.workspace = true
git-version = "0.3.5"
hex = "0.4"
munge = "=0.4.1"
serde_stacker = "0.1"
thiserror = "2.0"
toml = "0.8"
revm = "19.0"
c-kzg = { version = "1.0", features = ["serde"] }

[dev-dependencies]
eyre.workspace = true

[features]
default = []

