name: BridgeHistoryApi

on:
  push:
    branches:
      - main
      - staging
      - develop
      - alpha
    paths:
      - 'bridge-history-api/**'
      - '.github/workflows/bridge_history_api.yml'
  pull_request:
    branches:
      - main
      - staging
      - develop
      - alpha
    paths:
      - 'bridge-history-api/**'
      - '.github/workflows/bridge_history_api.yml'

defaults:
  run:
    working-directory: 'bridge-history-api'

jobs:
  check:
    # runs-on: ubuntu-latest
    # steps:
    # - name: Install Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.20.x
    # - name: Checkout code
    #   uses: actions/checkout@v2
    # - name: Lint
    #   run: |
    #     rm -rf $HOME/.cache/golangci-lint 
    #     make lint
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go get ./...
        make test
  goimports-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports
    - run: goimports -local scroll-tech/bridge-history-api/ -w .
    - run: go mod tidy
    # If there are any diffs from goimports or go mod tidy, fail.
    - name: Verify no changes from goimports and go mod tidy
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          exit 1
        fi
  
