name: RollupScan Backend

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'rollupscan/backend/**'
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'rollupscan/backend/**'

defaults:
  run:
    working-directory: 'rollupscan/backend'

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          profile: minimal
          toolchain: nightly-2022-08-23
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo build --release
          cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: nightly-2022-08-23
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy -- -D warnings

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2022-08-23
      - uses: Swatinem/rust-cache@v1
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run --all
