name: Utils

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'utils/**'
      - '.github/workflows/utils.yml'
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'utils/**'
      - '.github/workflows/utils.yml'

defaults:
  run:
    working-directory: 'utils'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      run: |
        rm -rf $HOME/.cache/golangci-lint 
        make lint
  goimports-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install goimports
      run: |
        go get golang.org/x/tools/cmd/goimports
    - run: goimports -local scroll-tech/utils/ -w .
    - run: go mod tidy -compat=1.17
    # If there are any diffs from goimports or go mod tidy -compat=1.17, fail.
    - name: Verify no changes from goimports and go mod tidy -compat=1.17
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          exit 1
        fi
